name: GitHub-Profile-Summary-Cards

on:
  schedule:
    # 毎日午前0時 (UTC) に実行する場合の例
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate
    # ↓↓↓ この permissions ブロックがジョブレベルに正しく設定されているか確認してください ↓↓↓
    permissions:
      contents: write # リポジトリのコンテンツへの書き込み権限を付与
    # ↑↑↑ ここまで ↑↑↑

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # checkout アクションも最新版を推奨します

      - name: GitHub Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          # ↓↓↓ GITHUB_TOKEN には secrets.GITHUB_TOKEN を指定します ↓↓↓
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          # 必要に応じて他のオプションもここに記述
          # 例:
          # UTC_OFFSET: 9 # 日本時間 (JST) にする場合
